# Generated by Django 3.0.5 on 2020-07-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idbyapi', models.CharField(max_length=200)),
                ('hotness', models.CharField(max_length=200)),
                ('activityHotness', models.CharField(max_length=200)),
                ('primaryCategory', models.CharField(max_length=200)),
                ('words', models.CharField(max_length=200)),
                ('similarArticles', models.CharField(max_length=200)),
                ('coins', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('publishedAt', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('source', models.CharField(max_length=200)),
                ('sourceDomain', models.CharField(max_length=200)),
                ('originalImageUrl', models.CharField(max_length=200)),
                ('lImageUrl', models.CharField(max_length=200)),
            ],
        ),
    ]
