# Generated by Django 3.0.5 on 2020-07-04 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CryptoNewsWebsite', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='newsdata',
        ),
    ]
