# Generated by Django 3.0.5 on 2020-07-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CryptoNewsWebsite', '0003_remove_newsdata_limageurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsdata',
            name='activityHotness',
        ),
        migrations.RemoveField(
            model_name='newsdata',
            name='coins',
        ),
        migrations.RemoveField(
            model_name='newsdata',
            name='description',
        ),
        migrations.RemoveField(
            model_name='newsdata',
            name='hotness',
        ),
        migrations.RemoveField(
            model_name='newsdata',
            name='idbyapi',
        ),
        migrations.RemoveField(
            model_name='newsdata',
            name='originalImageUrl',
        ),
        migrations.RemoveField(
            model_name='newsdata',
            name='primaryCategory',
        ),
        migrations.RemoveField(
            model_name='newsdata',
            name='publishedAt',
        ),
        migrations.RemoveField(
            model_name='newsdata',
            name='similarArticles',
        ),
        migrations.RemoveField(
            model_name='newsdata',
            name='source',
        ),
        migrations.RemoveField(
            model_name='newsdata',
            name='sourceDomain',
        ),
        migrations.RemoveField(
            model_name='newsdata',
            name='title',
        ),
        migrations.RemoveField(
            model_name='newsdata',
            name='url',
        ),
        migrations.RemoveField(
            model_name='newsdata',
            name='words',
        ),
        migrations.AddField(
            model_name='newsdata',
            name='listnews',
            field=models.ManyToManyField(related_name='_newsdata_listnews_+', to='CryptoNewsWebsite.newsdata'),
        ),
    ]
