# Generated by Django 3.0.5 on 2020-07-04 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CryptoNewsWebsite', '0004_auto_20200704_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsdata',
            name='listnews',
        ),
        migrations.AddField(
            model_name='newsdata',
            name='listnews',
            field=models.TextField(null=True),
        ),
    ]
