# Generated by Django 3.0.5 on 2020-07-05 09:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('CryptoNewsWebsite', '0005_auto_20200704_2330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsdata',
            name='listnews',
        ),
        migrations.AddField(
            model_name='newsdata',
            name='activityHotness',
            field=models.CharField(default=datetime.datetime(2020, 7, 5, 9, 15, 39, 418456, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsdata',
            name='coins',
            field=models.CharField(default=datetime.datetime(2020, 7, 5, 9, 15, 52, 949485, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsdata',
            name='description',
            field=models.CharField(default=datetime.datetime(2020, 7, 5, 9, 16, 5, 680925, tzinfo=utc), max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsdata',
            name='hotness',
            field=models.CharField(default=datetime.datetime(2020, 7, 5, 9, 16, 13, 505556, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsdata',
            name='idbyapi',
            field=models.CharField(default=datetime.datetime(2020, 7, 5, 9, 16, 18, 86363, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsdata',
            name='originalImageUrl',
            field=models.CharField(default=datetime.datetime(2020, 7, 5, 9, 16, 23, 228077, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsdata',
            name='primaryCategory',
            field=models.CharField(default=datetime.datetime(2020, 7, 5, 9, 16, 33, 208259, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsdata',
            name='publishedAt',
            field=models.CharField(default=datetime.datetime(2020, 7, 5, 9, 16, 38, 69210, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsdata',
            name='similarArticles',
            field=models.CharField(default=datetime.datetime(2020, 7, 5, 9, 16, 41, 913069, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsdata',
            name='source',
            field=models.CharField(default=datetime.datetime(2020, 7, 5, 9, 16, 48, 163075, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsdata',
            name='sourceDomain',
            field=models.CharField(default=datetime.datetime(2020, 7, 5, 9, 16, 55, 132720, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsdata',
            name='title',
            field=models.CharField(default=datetime.datetime(2020, 7, 5, 9, 16, 58, 487683, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsdata',
            name='url',
            field=models.CharField(default=datetime.datetime(2020, 7, 5, 9, 17, 0, 632212, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsdata',
            name='words',
            field=models.CharField(default=datetime.datetime(2020, 7, 5, 9, 17, 3, 260234, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
    ]
