# Generated by Django 3.0.5 on 2020-07-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CryptoNewsWebsite', '0006_auto_20200705_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsdata',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='newsdata',
            name='source',
            field=models.TextField(),
        ),
    ]
