# Generated by Django 3.0.5 on 2020-07-05 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CryptoNewsWebsite', '0007_auto_20200705_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsdata',
            name='activityHotness',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='newsdata',
            name='coins',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='newsdata',
            name='hotness',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='newsdata',
            name='originalImageUrl',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='newsdata',
            name='primaryCategory',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='newsdata',
            name='similarArticles',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='newsdata',
            name='sourceDomain',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='newsdata',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='newsdata',
            name='url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='newsdata',
            name='words',
            field=models.TextField(),
        ),
    ]
