# Generated by Django 3.0.5 on 2020-07-31 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CryptoNewsWebsite', '0010_auto_20200705_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='bitcoinnewsdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idbyapi', models.CharField(max_length=200)),
                ('hotness', models.TextField()),
                ('activityHotness', models.TextField()),
                ('primaryCategory', models.TextField()),
                ('words', models.TextField()),
                ('similarArticles', models.TextField()),
                ('coins', models.TextField()),
                ('description', models.TextField()),
                ('publishedAt', models.TextField()),
                ('title', models.TextField()),
                ('url', models.TextField()),
                ('source', models.TextField()),
                ('sourceDomain', models.TextField()),
                ('originalImageUrl', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ethereumnewsdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idbyapi', models.CharField(max_length=200)),
                ('hotness', models.TextField()),
                ('activityHotness', models.TextField()),
                ('primaryCategory', models.TextField()),
                ('words', models.TextField()),
                ('similarArticles', models.TextField()),
                ('coins', models.TextField()),
                ('description', models.TextField()),
                ('publishedAt', models.TextField()),
                ('title', models.TextField()),
                ('url', models.TextField()),
                ('source', models.TextField()),
                ('sourceDomain', models.TextField()),
                ('originalImageUrl', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ripplenewsdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idbyapi', models.CharField(max_length=200)),
                ('hotness', models.TextField()),
                ('activityHotness', models.TextField()),
                ('primaryCategory', models.TextField()),
                ('words', models.TextField()),
                ('similarArticles', models.TextField()),
                ('coins', models.TextField()),
                ('description', models.TextField()),
                ('publishedAt', models.TextField()),
                ('title', models.TextField()),
                ('url', models.TextField()),
                ('source', models.TextField()),
                ('sourceDomain', models.TextField()),
                ('originalImageUrl', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='topnewsdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idbyapi', models.CharField(max_length=200)),
                ('hotness', models.TextField()),
                ('activityHotness', models.TextField()),
                ('primaryCategory', models.TextField()),
                ('words', models.TextField()),
                ('similarArticles', models.TextField()),
                ('coins', models.TextField()),
                ('description', models.TextField()),
                ('publishedAt', models.TextField()),
                ('title', models.TextField()),
                ('url', models.TextField()),
                ('source', models.TextField()),
                ('sourceDomain', models.TextField()),
                ('originalImageUrl', models.TextField()),
            ],
        ),
    ]
